repos:
  - repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0                 # use the most recent version
    hooks:
      # Hooks using native
      - id: cpplint              # linter (or style-error checker) for Google C++ Style Guide